import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :bn_apis, BnApisWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4002],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  secret_key_base: "dVNTb8DiLITnihqBvQV5IqaZq4Unbsx+bntnGFh7FDjYMlP9B9oaET7qOUT+eFek",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :bn_apis, BnApisWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/bn_apis_web/(live|views)/.*(ex)$",
      ~r"lib/bn_apis_web/templates/.*(eex)$"
    ]
  ]

config :ex_aws,
  access_key_id: "AKIAQUMNIVUXMK6OYPIF",
  secret_access_key: "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",
  temp_bucket: "bn-files-temp",
  files_bucket: "bn-files-temp"

config :bn_apis,
  server_env: "development",
  twilio_account_sid: "AC7dbe29c2040594f7b3ccde3b9276de27",
  twilio_auth_token: "030e6adcc00152d2fc498d3153fc7bc8",
  twilio_endpoint: "https://api.twilio.com/2010-04-01/Accounts/",
  twilio_from: "MGeb333da730c996ed24dfbfed7070ec47",
  bulksms_url: "https://www.perfectbulksms.co.in/Sendsms.aspx",
  bulksms_apikey: "",
  bulksms_entity_id: "",
  default_dev_twilio_to: "+919711227605",
  whitelisted_dev_twilio_tos: "phone_number1, phone_number2, phone_number3",
  apxor: %{
    enable_apxor_sdk: true,
    ios_app_id: "",
    android_app_id: ""
  },
  mobtexting: %{
    token: "abcdeffgthtasdfdf",
    send_endpoint: "https://portal.mobtexting.com/api/v2/sms/send",
    enabled: "false"
  },
  sendbird: %{
    application_id: "18B983A0-1C8B-4C20-A0AD-7491425A9E88",
    api_token: "d198545a4508714ba87db47049eb8bfca427f462"
  },
  more_vals: "",
  imgix_domain: "https://bn-stag.imgix.net",
  secret_salt: "hare_krishna",
  sms_token: "6VWwBfbh2yd",
  deep_link_app_version: "102028",
  slack_url: "https://slack.com/api/chat.postMessage",
  slack_token: "xoxp-690718612257-696590235796-698919267143-b422af4a5cd752622cc4b3cbda11e136",
  slack_channel: "CLK644KML",
  slack_building_channel: "CNR0FF9DY",
  match_plus_customer_support_number: "+919711227605",
  match_plus_original_price: 1999,
  match_plus_price: 1,
  match_plus_offer_title: "Introductory offer",
  match_plus_offer_text: "100% off",
  customer_support_number: "+919711227605",
  mumbai_customer_support_number: "+919711227605",
  default_sms_number: "+919819619866",
  should_send_sms: "false",
  mumbai_customer_support_person: "ULGHC6XPE",
  pune_customer_support_person: "UP39V93PW",
  default_customer_support_person: "ULANKKPGR",
  # Urls must without trailing slash
  hosted_domain_url: "http://localhost:4000",
  deep_link_hosted_domain_url: "http://localhost:4000",
  playstore_app_url: "https://play.google.com/store/apps/details?id=test",
  bn_web_base_url: "https://website.staging.brokernetwork.app",
  meta_service_url: "https://meta.staging.anarock.com",
  ivr_masked_number: "9711227605",
  ivr_app_id: "123",
  ivr_sid: "abc",
  ivr_token: "abcdef44b782a495eb54b9564addfb2e2d52625f",
  virtual_number: "09711227605",
  places_key: "AIzaSyDKbrToaeyC_rzgfd8DWncyTvgh4crtXp8",
  db_query_key: "ABCD",
  leadsquared_url: "https://api-in21.leadsquared.com",
  leadsquared_access_key: "u$r88105d91e8c74b3ac22770f73330625c",
  leadsquared_secret_key: "fe28f09aa44ae8e160d382adc66ba7c1ba17d04a",
  razorpay_url: "https://api.razorpay.com/",
  razorpay_username: "rzp_test_xTCm1a65FqNCKF",
  razorpay_password: "BQ8Rlsj10ABVhgW9HGXeJz5P",
  razorpay_account_number: "4564568236926553",
  razorpay_match_plus_plan_id: "plan_IgOBxAxFkDkyUW",
  razorpay_webhook_secret_key: "W3p96v8WBiujm8yHdgrLYy73XZFaV2ri",
  razorpay_ifsc_url: "https://ifsc.razorpay.com/",
  attestr_auth_key: "",
  attestr_url: "https://api.attestr.com/api/v1/public/finanx/vpa",
  attestr_gstin_url: "https://api.attestr.com/api/v1/public/corpx/gstin",
  attestr_pan_url: "https://api.attestr.com/api/v1/public/checkx/pan",
  paytm_merchant_key: "YM&Qlor6Gl&3LIz@",
  paytm_merchant_id: "rpBxgE04953728903612",
  paytm_url: "https://securegw.paytm.in/",
  paytm_website_mode: "DEFAULT",
  paytm_subscription_amount: "1.00",
  paytm_subscription_validity_in_days: 7,
  paytm_subscription_frequency_unit: "WEEK",
  paytm_subscription_enabled: false,
  slash_url: "https://brainguru.slashrtc.in/",
  slash_username: "slashadmin",
  slash_password: "pFK![8uVUVq46rtr",
  bn_apis_base_url: "https://api.staging.brokernetwork.app/",
  builder_chat_min_supported_version: "1000009000",
  display_project_filters: "false",
  rera_validation_url: "https://panel.brokernetwork.app/api/v0/validate-rera",
  s2c_api_token: "2351b584-1def-11ed-861d-0242ac120002",
  bn_username_in_s2c: "4bnet",
  bn_pwd_in_s2c: "Aug@2022",
  s2c_api_url: "https://conference.simple2call.in/ab_api.php",
  piramal_authentication_key: "7d5a029a-1f05-11ed-861d-0242ac120002",
  hl_manager_phone_number: "918657946810",
  routed_name: "Routed",
  piramal_sfdc_url: "https://prl--prlapp.sandbox.my.salesforce.com/services/apexrest/CP_Mobile_App/BrokerageUpdateBNtoSFDC",
  salesforce_auth_token_url: "https://test.salesforce.com/services/oauth2/token",
  salesforce_grant_type: "password",
  salesforce_client_id: "3MVG9Se4BnchkASnJ0eDEZX9z9D7w5.Useb0G1N5w8TloI60n3z2sLOgAP.kQJMu4cDVDD6R8ZoiI52dTnngF",
  salesforce_client_secret: "ABBF4E5B2A89FD49A3FE015D63A715BDA2D7CA9CE54AD3991560E98276387FB4",
  piramal_sfdc_username: "aniket.khillari1010@stetig.in",
  piramal_sfdc_password: "Mobileapp@123u0vS6ZiRg9RNJHRVr9WeO1jpY",
  youtube_api_key: "AIzaSyCllFVGze_dRjtMYwVVZw_HQPWyGiEeVjk",
  youtube_api_base_url: "https://youtube.googleapis.com/youtube/v3/videos?",
  should_send_whatsapp: "true",
  whatsapp_token: "",
  billdesk_redirect_url: "https://api.staging.brokernetwork.app/billdesk/return_url",
  create_order_base_url: "https://website.staging.brokernetwork.app/billdesk"

config :exq,
  name: Exq,
  host: "127.0.0.1",
  port: 6379,
  namespace: "bn_apis_dev_exq",
  queues: [
    {"process_post_matches", 2},
    {"matches_notification", 2},
    {"send_notification", 2},
    {"team_notification", 2},
    {"custom_notification", 2},
    {"story", 1},
    {"push_notification", 5},
    {"dnd_removal", 1},
    {"personalised_sales_kit_generator", 20},
    {"broker_kit_generator", 20},
    {"broker_kyc_notification", 2},
    {"leadsquared_lead_push", 2},
    {"slash_lead_push", 2},
    {"homeloan", 2},
    {"payments", 1},
    {"employee_payments", 1},
    {"update_subscription_status", 1},
    {"send_owner_notifs", 20},
    {"send_new_project_notifications", 20},
    {"send_new_story_creatives_notifications", 20},
    {"send_transactions_notif", 20},
    {"payments", 1},
    {"employee_payments", 1},
    {"update_subscription_status", 1},
    {"invoices", 1},
    {"sendbird", 2},
    {"send_rewards_enabled_notification", 20},
    {"send_changes_requested_fcm_notification", 4},
    {"send_whatsapp_message", 20},
    {"reminders", 2},
    {"campaign", 2},
    {"dev_poc_notification_queue", 2},
    {"send_new_invoice_notification", 2},
    {"invoice_payout", 2}
  ],
  poll_timeout: 50,
  scheduler_poll_timeout: 200,
  scheduler_enable: true,
  max_retries: 0,
  shutdown_timeout: 5000,
  start_on_application: false

# Do not include metadata nor timestamps in development logs
config :logger, level: :debug, truncate: :infinity

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :bn_apis, BnApis.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "brokernetwork",
  database: "bn_apis_production",
  hostname: "dev-db.cezgkxgymvnv.ap-south-1.rds.amazonaws.com",
  port: 5432,
  types: BnApis.PostgresTypes,
  stacktrace: true,
  pool_size: 10

config :redix,
  host: "127.0.0.1",
  port: 6379

config :pigeon, :fcm,
  fcm_default: %{
    key: "AAAAKcGPGEc:APA91bGMsZqairIhjydRtvOFHFSoO08OrP2WUdv8BhoPv1FSioe_qbOXoiEmdAFlunetUEBtXv7afeO-8ESnuNwoMf9qz8fPdxyKXixSWhiAG-r5yYkTaApN0_HS68VVVDEUcsFQz_Xe"
  }

config :bitly, access_token: "b6afcc2a8fb16c96295c2e9a4b1317131cee64e9"

config :bn_payments,
  http_client_opts: [],
  merchant_id: "fake",
  client_id: "fake",
  secret_key: "fake",
  bill_desk_endpoint: "",
  client_module: BnPayments.Stub

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :bn_apis, BnApis.Digio.API,
  digio_api_base_url: "https://api.digio.in",
  digio_esign_base_url: "https://app.digio.in",
  digio_username: "",
  digio_password: ""

config :bn_apis, BnApis.Signzy.API,
  signzy_base_url: "https://sandbox-preproduction.signzy.tech/api/v2",
  signzy_username: "brokernetwork_test",
  signzy_password: "aYG6T77rVMjFdp3HSm2u",
  signzy_callback_url: "https://api.staging.brokernetwork.app/callbacks/pan",
  signzy_bn_email_contact: "dev@brokernetwork.app"
